### ISSUE TITLE
Same icons, different aliases

### ISSUE THREAD

**Issue by smajl** [thomaspark/glyphsearch#39]
I was about to code search engine for FontAwesome in Angular this holidays for myself, but found this. :)

Anyway, I immediately noticed, that there are some issues with aliases. I expect to get the same icon from FontAwesome and IcoMoon when I type "help", but FontAwesome icon is missing this alias (although it's the same exact icon). This was the first thing I typed, so there could be more.. or not. :)

Anyway, good work.

BTW: This could by somewhat self-maintained if user labeling is implemented as suggested in https://github.com/thomaspark/glyphsearch/issues/20

**Comment by thomaspark** [comment]
Added missing tags for help, along with tags for logos, transportation, gender, and a few others.

Feel free to open an issue if there are any glaring omissions or mistakes.
