### ISSUE TITLE
Icons not clickable in Chrome on first load

### ISSUE THREAD

**Issue by pagelab** [thomaspark/glyphsearch#40]
You probably have to clear the cache to see this.

![video2](https://cloud.githubusercontent.com/assets/1451087/5805610/9cc56eac-9ff7-11e4-937a-74fa99657c0e.gif)

**Comment by redox** [comment]
I've already spotted that behavior while rendering the whole page using JavaScript. Didn't manage to debug it however :/ Any chance some of you guys are JS-event masters understanding where the click event is triggered?

**Comment by jenil27** [comment]
Yes I also spotted it, this seems to be an issue because of ZeroClipboard but not exactly sure.

**Comment by pagelab** [comment]
Strangely, this never happens on localhost...

**Comment by peterblazejewicz** [comment]
this block:
https://github.com/thomaspark/glyphsearch/blob/gh-pages/js/index.js#L141-L162
is never called in Chrome in scenario as described above - investigating

**Comment by thomaspark** [comment]
Upgrading ZeroClipboard from 1.2.3 to 2.2.0 (8c5acd6c5dc480c4ff15f6e59513b443b1cc5b40) seems to have fixed it. Can you guys confirm?

**Comment by peterblazejewicz** [comment]
@thomaspark Yes, I cannot repeat problem use dev tools/disabled cache (at least on development machine at work)

**Comment by pagelab** [comment]
@thomaspark Working fine now, thanks!
