### ISSUE TITLE
no `master` branch?

### ISSUE THREAD

**Issue by grimen** [thomaspark/glyphsearch#51]
This project only have `gh-pages` branch, which is confusing for potential contributors.

**Comment by grimen** [comment]
Still think this should be taken into consideration as `master` branch is default in all 99.99% of all GitHub projects with ot without GitHub pages. The fix is easy and generic:

```
[remote "origin"]
      url = https://github.com/<github_user>/<repo_name>
      fetch = +refs/heads/*:refs/remotes/origin/*
      push = refs/heads/master:refs/heads/master
      push = refs/heads/master:refs/heads/gh-pages
```

Source: [Stackoverflow: "Github: Mirroring gh-pages to master"](http://stackoverflow.com/questions/5807459/github-mirroring-gh-pages-to-master)

**Comment by thomaspark** [comment]
Was using `gh-pages` for personal convenience, but given potential and current contributors, I've added a `master` branch as default. I'm fine with merging but mirroring pushes looks handy.

**Comment by grimen** [comment]
Great!
