### ISSUE TITLE
Error in icons-foundation.json

### ISSUE THREAD

**Issue by NeverWise** [thomaspark/glyphsearch#73]
Hi,
I found an error in the icons-foundation.json.
these two lines
`{"name": "upload-cloud", "unicode": ""},`
`{"name": "usb","unicode": "f20b"},`
should be
`{"name": "upload-cloud", "unicode": "f20b"},`
`{"name": "usb","unicode": "f20d"},`

**Comment by thomaspark** [comment]
@NeverWise, thanks for the bug report!
