### ISSUE TITLE
Material icons not working

### ISSUE THREAD

**Issue by simplesquare1** [thomaspark/glyphsearch#74]
Hi Thomas, 

First of all...thank you very much for the glyphSearch. It's amazing tool!

Problem I found is that material icons are not working. I am not developer, so can't help you much. But I believe you know how to fix this ;).

Thanks
Jana

**Comment by thomaspark** [comment]
Hi @simplesquare1, thanks for the heads up. Can you tell me what happens when you try with material icons versus other icons that it isn't working for you? Does nothing happen when you click? Or the wrong text is copied to clipboard?
